version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: 'postgres'
    ports:
      - "4444:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'DDsspp20'
      
